import { useState, useCallback, useEffect, useRef } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useAuth } from '../../../../context/AuthContext';
import {
  getAlumnosPorPromocion,
  getCursosPorDocente,
  getEstudiantesPorCurso,
  getNotasPorEstudiante,
  getPagosPorEstudiante,
  getPagosPendientesValidados,
} from '../../../../services/reportesApiService';
import type { FiltrosState, ResultadosReporte } from '../types/reportes.types';

const FILTROS_INICIALES: FiltrosState = {
  tipo: 'alumnos-por-promocion',
  semesterId: '',
  programId: '',
  yearPromotion: new Date().getFullYear(),
  teacherId: '',
  courseId: '',
  studentId: '',
  studentNameSearch: '',
  estadoNota: 'TODOS',
  estadoPago: 'TODOS',
};

export type { ResultadosReporte };

export function useReportes() {
  const { token } = useAuth();
  const [searchParams] = useSearchParams();

  const inicialFiltros = { ...FILTROS_INICIALES };
  const paramTipo = searchParams.get('tipo') as any;
  if (paramTipo) inicialFiltros.tipo = paramTipo;
  const paramStudentId = searchParams.get('studentId');
  if (paramStudentId) inicialFiltros.studentId = paramStudentId;

  const [filtros, setFiltros] = useState<FiltrosState>(inicialFiltros);
  const [resultados, setResultados] = useState<ResultadosReporte>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const hasAutoGenerated = useRef(false);

  const handleFiltroChange = useCallback(
    <K extends keyof FiltrosState>(campo: K, valor: FiltrosState[K]) => {
      setFiltros((prev) => ({ ...prev, [campo]: valor }));
      // limpiar resultados al cambiar tipo
      if (campo === 'tipo') {
        setResultados(null);
        setError(null);
      }
    },
    []
  );

  const handleGenerar = useCallback(async () => {
    if (!token) return;
    setIsLoading(true);
    setError(null);
    setResultados(null);

    try {
      switch (filtros.tipo) {
        case 'alumnos-por-promocion': {
          const filas = await getAlumnosPorPromocion(token, filtros.yearPromotion);
          setResultados({ tipo: 'alumnos-por-promocion', filas });
          break;
        }
        case 'cursos-por-docente': {
          if (!filtros.teacherId) throw new Error('Selecciona un docente.');
          const filas = await getCursosPorDocente(token, filtros.teacherId);
          setResultados({ tipo: 'cursos-por-docente', filas });
          break;
        }
        case 'estudiantes-por-curso': {
          if (!filtros.courseId) throw new Error('Selecciona un curso.');
          const filas = await getEstudiantesPorCurso(token, filtros.courseId);
          setResultados({ tipo: 'estudiantes-por-curso', filas });
          break;
        }
        case 'notas-por-estudiante': {
          if (!filtros.studentId) throw new Error('Selecciona un estudiante.');
          const filas = await getNotasPorEstudiante(token, filtros.studentId);
          setResultados({ tipo: 'notas-por-estudiante', filas });
          break;
        }
        case 'pagos-por-estudiante': {
          const filas = await getPagosPorEstudiante(token, filtros.studentNameSearch);
          setResultados({ tipo: 'pagos-por-estudiante', filas });
          break;
        }
        case 'pagos-pendientes-validados': {
          const filas = await getPagosPendientesValidados(token, filtros.estadoPago);
          setResultados({ tipo: 'pagos-pendientes-validados', filas });
          break;
        }
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Error al generar el reporte.');
    } finally {
      setIsLoading(false);
    }
  }, [token, filtros]);

  const handleLimpiar = useCallback(() => {
    setFiltros(FILTROS_INICIALES);
    setResultados(null);
    setError(null);
  }, []);

  useEffect(() => {
    if (token && searchParams.get('auto') === 'true' && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerar();
    }
  }, [token, searchParams, handleGenerar]);

  return {
    filtros,
    resultados,
    isLoading,
    error,
    handleFiltroChange,
    handleGenerar,
    handleLimpiar,
  };
}
